// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsvctnxiaquebimrxvoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzdmN0bnhpYXF1ZWJpbXJ4dm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzE1MDEsImV4cCI6MjA2NDU0NzUwMX0._S6ZoYf5H44R5kvHL6I73lHGLJ1YP8P0tMHNOyfkeKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);